export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';

export const CATEGORIES_FETCHING = 'CATEGORIES_START_FETCHING';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';
export const CATEGORIES_FETCH_REQUEST = 'CATEGORIES_FETCH_REQUEST';

export const PRODUCTS_FETCHING = 'PRODUCTS_START_FETCHING';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const CATEGORY_PRODUCTS_FETCHED = 'CATEGORY_PRODUCTS_FETCHED';
export const SINGLE_PRODUCT_FETCHED = 'SINGLE_PRODUCT_FETCHED';
export const PRODUCT_FETCH_REQUESTED = 'PRODUCT_FETCH_REQUESTED';
export const CATEGORY_PRODUCTS_FETCH_REQUEST =
    'CATEGORY_PRODUCTS_FETCH_REQUEST';
export const SINGLE_PRODUCT_FETCH_REQUEST = 'SINGLE_PRODUCT_FETCH_REQUEST';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
