type Query {
    categories: [Category]
    products: [Product]
}

"Category object"
type Category {
    _id: ID!
    name: String!
    image: String
    updatedAt: String
    createdAt: String
}

"Product object"
type Product {
    _id: ID!
    name: String!
    description: String
    image: String
    quantity: Int
    price: Int
    """
    Category ID
    """
    category: ID
    updatedAt: String
    createdAt: String
}
