type Query {
    categories: [Category]
    products: [Product]
    categoryProducts(category_id: String!): [Product]
    product(product_id: String!): Product
}

type Mutation {
    authLogin(email: String!, password: String!): LoginPayload
    authSignup(
        firstname: String!
        lastname: String!
        email: String!
        password: String!
    ): SignupPayload
}

"Category object"
type Category {
    _id: ID!
    name: String!
    image: String
    updatedAt: String
    createdAt: String
}

"Product object"
type Product {
    _id: ID!
    name: String!
    description: String
    image: String
    quantity: Int
    price: Int
    qty: Int
    """
    Category ID
    """
    category: ID
    updatedAt: String
    createdAt: String
}

type LoginPayload {
    token: String
    userId: String
    error: String
}

type SignupPayload {
    error: String
    success: Boolean!
}
